### ISSUE TITLE
Please Confirm OSS's License Data

### ISSUE THREAD

**Issue by yongyongsi** [osori-db/osori-db.github.io#38]
**Describe the bug**
OSS's license information seems to be incorrect. I would appreciate it if you could check the data once.
OSS Name : bcpg-jdk15on
Osori URL : https://www.olis.or.kr/ossDetail.do?id=9932&page=1
Package URL : https://mvnrepository.com/artifact/org.bouncycastle/bcpg-jdk15on/1.64
Package Repository URL : https://repo1.maven.org/maven2/org/bouncycastle/bcpg-jdk15on/1.64/bcpg-jdk15on-1.64.pom

The package repository url refers to the Bouncy Castle license(MIT License) and Apache License 1.1. However, the Osori page only mentions Apache License 2.0. Please check.

**Screenshots**

**Additional context**

**Comment by MoonkiHong** [comment]
@soimkim Please take a look at this. 🙏

**Comment by soimkim** [comment]
@yongyongsi ,
Because the source file included only Apache-2.0, the license information was saved incorrectly.
Accordingly, the license information was updated as follows.
![image](https://github.com/osori-db/osori-db.github.io/assets/4284712/dc13f52e-f568-47dd-b0d9-bee17f97b699)

Thank you for reporting the issue.
