### ISSUE TITLE
[Bug] No searched result in the Korean page

### ISSUE THREAD

**Issue by MoonkiHong** [osori-db/osori-db.github.io#4]
- Issue definition
  - Searched result only shows its English documentation when using its Korean language version.
- Reproduction path
  - From the search bar in any of documentation page > Try to search anything using the keyword in Korean > No result
- Expected operation
  - Searched result should be represented as its Korean documentation properly.
  - Reference: try to adopt `lunr.ko.js`, `lunr.stemmer.support.js` from https://github.com/MihaiValentin/lunr-languages
    - You can get more guidance from [Ref 1](https://github.com/just-the-docs/just-the-docs/discussions/437) and [Ref 2](https://github.com/just-the-docs/just-the-docs/issues/470).

**Comment by fesfojas** [comment]
Hi Moonki! I'll explain my progress in resolving this bug here:

I already have used both lunr.ko.js and lunr.stemmer.support.js. What these Javascript plugins do is that they allow Korean characters to be inputted in the search bar. This is because by default, Korean characters is not supported in Just The Docs that's why I used these plugins.

So now, we can already type Korean characters in the search bar, but there is still one problem that remains.

- Just The Docs builds a search index during the website's initial deployment and it is based on the site's default language.
- Currently since English is the default language of the site, the search index is only built in English and no search index is made for Korean.  
- Vice versa, if I make the site's default language to Korean, then the search index is built based on the default language and I can only search in Korean, not in English alphabet.


Currently, I am working on my solution to be able to dynamically make a search index json file by using JavaScript.

**Comment by MoonkiHong** [comment]
> Hi Moonki! I'll explain my progress in resolving this bug here:
> 
> I already have used both `lunr.ko.js` and `lunr.stemmer.support.js`. What these Javascript plugins do is that they allow Korean characters to be inputted in the search bar. This is because by default, Korean characters is not supported in Just The Docs that's why I used these plugins.
> 
> So now, we can already type Korean characters in the search bar, but there is still one problem that remains.
> 
> * Just The Docs builds a search index during the website's initial deployment and it is based on the site's default language.
> * Currently since English is the default language of the site, the search index is only built in English and no search index is made for Korean.
> * Vice versa, if I make the site's default language to Korean, then the search index is built based on the default language and I can only search in Korean, not in English alphabet.
> 
> Currently, I am working on my solution to be able to dynamically make a search index json file by using JavaScript.

Yeah, right. I expected the same from the current source code in the repo. We are on the same page, @fesfojas Let me know any update from yours. Just for your information, I would like to suggest you to configure the Korean as the default language since its first launch will be for the Korean community.

**Comment by fesfojas** [comment]
Thank you Moonki :) 
This is noted. Will configure Korean as the default language.

**Comment by fesfojas** [comment]
Hi Moonki, Korean is now set as the default language. You may now search using Korean.

For now, when you switch to English, the search won't work. Will update immediately once I was able to resolve this. Thannk you :)

**Comment by MoonkiHong** [comment]
Copy that.

**Comment by fesfojas** [comment]
Hi Moonki! :)
I have already applied a solution to this bug and so far, the testing on my end seems like it is now working properly. 

You may also try to test on your side if the issue has already been resolved. Thank you. :)

**Comment by MoonkiHong** [comment]
We are checking out if there is more things to be resolved for this issue. Please stay tuned. Once confirmed, I will close this issue as resolved. 🙏

**Comment by MoonkiHong** [comment]
Seems alike this issue has been resolved, So close this issue and we will be back when we encounter the related bug thru a new ticket. Thank you!
